### PR TITLE
Simple configuration option to disable html wrap

### PR DESCRIPTION
**Pull request by actuosus**
Added configuration to disable wrapping of embed html data.

### CODE REVIEW

**Comment by iparamonau** [comment]
Thanks. Can you give an example?

**Comment by actuosus** [comment]
You can set `CONFIG.R.disableSizeWrapper = true`. After that you can get see no wrapping at `html` key in API response `/iframely?refresh=true&url=https%3A%2F%2Fwww.facebook.com%2FJuliusmagic%2Fvideos%2F1178542432223240%2F`:

```
"html": "<iframe src=\"undefined/render?uri=https%3A%2F%2Fwww.facebook.com%2FJuliusmagic%2Fvideos%2F1178542432223240%2F\" frameborder=\"0\" allowfullscreen></iframe>"
```

**Comment by iparamonau** [comment]
Thanks for reminding. Actually, this option isn't used for over 4 yrs now and should be removed altogether. What's your use case for it?

**Comment by actuosus** [comment]
Oh. We have an issue with [vertical video from Facebook](https://www.facebook.com/100013440226934/videos/239568426501163/). [Facebook oEmbed API returns|https://www.facebook.com/plugins/video/oembed.json/?url=https%3A%2F%2Fwww.facebook.com%2FJuliusmagic%2Fvideos%2F1178542432223240%2F&format=json] improper meta data for vertical video. Iframely wraps the html with 16:9 styling and we have improper layout for iframe. So I removed wrapping.

**Comment by iparamonau** [comment]
In that case you make the problem even worse as iFrame will default to something like 300x150.

To fix the problem with FB specifically, you can do two things: 
 - skip our renders altogether via `SKIP_IFRAMELY_RENDERS: true` in your local config, 
- or add [iframely.js](https://github.com/itteco/iframely/blob/master/static/js/iframely-for-iframe.js) script to your page. It will adjust the height of rendered iFrames as necessary. 

You can see it in action in your local /debug tool when you have the server running.

**Pull request closed without merging**
