### PR TITLE
Fixes #248. Enforcing Node version in Docker to be 12.13.1 to workaro…

### LINKED ISSUE #248: Error loading shared library /iframely/node_modules/iltorb/build/bindings/iltorb.node: Exec format
When I run with docker from this [document](https://iframely.com/docs/host)

Its have an error like this and I cannot use iframely with docker.
Screen Shot 2563-04-17 at 15 59 27

### PR DESCRIPTION
**Pull request by deshetti**
- Fixes #248. 
- Enforce Node version in Docker to be 12.13.1 to workaround the timeout issue. 
- Upstream changes from @joltcan PR #294

### CODE REVIEW

**Comment by nleush** [comment]
Thanks for PR. Accepted in `develop`: https://github.com/itteco/iframely/commit/3e6c05471f8a6ba50cb55344b70128f00d906bff.

**Comment by nleush** [comment]
Hi, @deshetti! Thanks for your PR. As I see you have changed `node` version to `12.13.1-alpine`. But I can't fine that tag in supported tags list: https://hub.docker.com/_/node. Is it ok?

**Comment by deshetti** [comment]
@nleush There is a 12.13.1-alpine in the tags. https://hub.docker.com/layers/node/library/node/12.13.1-alpine/images/sha256-3881b565f3dade1e8d7b752b5da727eb3b483a791a09b5e0dcf405262a18a384?context=explore

**Comment by deshetti** [comment]
@nleush will this PR be merged? Let me know if you need anything else from me.

**Comment by nleush** [comment]
@deshetti I've just picked your commit into develop branch: https://github.com/itteco/iframely/commit/49fd3680e9ae7c078be5f5ddbe6e8cf9cfca7fa5. Thanks for PR.

**Pull request closed without merging**
