### PR TITLE
Implement ENVRMNT Support

### PR DESCRIPTION
**Pull request by asap**
Add support for ENVRMNT from Verizon. VR Embeds are provided with
via url and a second api is scraped for meta data.

Returns corresponding embed html code, with scripts to support various
JS browser workarounds and styling.

### CODE REVIEW

**Comment by nleush** [comment]
Hi,

When I try test plugin with test url specified I see no video and following error in browser debug console:

    angular-1.5.5.min.js:103
    GET http://media.envrmnt.com/media/vrexperience/a4e56f72-5be9-4b08-bf59-51dd6b2b072f
    404 (Not Found)

**Comment by asap** [comment]
@nleush Odd. That call should be `http://cloud-www.envrmnt.com/#/video/a4e56f72-5be9-4b08-bf59-51dd6b2b072f?4a41b15c-dce0-44e5-879f-c0d4b05713ab`

What's the full url you're using so I can try locally?

**Comment by nleush** [comment]
Yes, i test this one: http://cloud-www.envrmnt.com/#/video/a4e56f72-5be9-4b08-bf59-51dd6b2b072f?4a41b15c-dce0-44e5-879f-c0d4b05713ab

**Comment by nleush** [comment]
If I remove 'inline' rel from link I see another error:

    all.min.js:1 Error 404 Object {errorMessage: "No VR Experience could be found for that Id"}

**Comment by asap** [comment]
Try this url: http://www.envrmnt.com/#/video/6ec3f3f8-69f4-4b29-b64d-14992e19005f?3e6d6290-cd65-46b8-b4a6-1b1b6e3674d9

I believe I may have accidentally shared non-production url.

**Comment by nleush** [comment]
Yes, that one works. Thank you.

**Comment by nleush** [comment]
Thanks for PR.

This is now merged to 'develop' branch.

**Pull request closed without merging**
