### PR TITLE
Latest alpine + Makefile for docker builds

### PR DESCRIPTION
**Pull request by joltcan**
Not sure if you are interested in some changes to make docker building easier.

This is what I use, so feel free to merge.

### CODE REVIEW

**Comment by iparamonau** [comment]
Thanks, this looks great, although we don't use docker ourselves... 
So can I ask for some help moving the doc changes to the SETUP doc's [docker section](https://github.com/itteco/iframely/blob/master/docs/SETUP.md#docker)?

. If need be or you feel like it, it would be fine to include/change just summary in the `SETUP.md` doc, and then have all details linked as new file `DOCKER.md`

**Comment by joltcan** [comment]
Ill makr something up, cheers!


-- 
Fredrik Lundhag
wire.com: @jolt

**Comment by joltcan** [comment]
I'm no github expert., so tell me if this looks ok?

**Comment by iparamonau** [comment]
Thanks, good enough - the PR is now merged into `develop` branch. We'll revise the docs if needed. Thanks!

**Pull request closed without merging**
