### PR TITLE
Added customisations to the Google Maps plugin

### PR DESCRIPTION
**Pull request by suprememoocow**
I'm not sure if this is the best way to do this, so please let me know if there's a better way!

This PR adds the ability to customise the height and width of the static Google Maps image and also allows the `app` embed to be disabled for Google Maps by specifying `disableApp: true` in the config.

The default behaviour remains the same (250x250 pixels, app enabled) but can be changed like so:

```
    "google.maps": {
      disableApp: true,
      staticWidth: 400,
      staticHeight: 250
    }
```

### CODE REVIEW

**Comment by iparamonau** [comment]
Oops, sorry. Apparently haven't seen this PR until now. 
Yes, it's the right way to add options. We'll test and merge. Thanks!

**Comment by iparamonau** [comment]
@nleush the only problem I see is that `config` can be null as some people may not have new Google Maps settings in local configs at all. Especially those who already have the systems running for a while. Also, need to add it to the sample config too.

**Comment by suprememoocow** [comment]
Hi guys, just to let you know, after submitting this PR, I actually disabled this embed on our site as I've found it to be too unreliable - it currently doesn't work with map links outside of the US (which now default to local domains, for example: in South Africa, maps redirects to [www.google.co.za](https://www.google.co.za/maps/@-34.1414029,18.3354603,14z?hl=en)..). I think the regexps for matching google map URLs need to be extended a bit to support other domains, including things like:

* https://www.google.fr/maps/ (second level domain)
* https://www.google.com.au/maps/ (third level domain, but not `.co.XX`)

**Comment by suprememoocow** [comment]
That said, I'll update the PR soon with your suggested changes...

**Comment by iparamonau** [comment]
If you could provide the URLs which don't work - it would help us. 
The problem with Google Maps is that they have new URL scheme now, and this plugin handles the old ones. 
However, oddly enough, Google 301 re-directs our user-agent for _all_ new URLs to the old URL scheme, so our old code works, and more over, we can't write a parser for new URLs as it won't be used anyway. 
It's a funny world.

**Comment by suprememoocow** [comment]
Yeah, external data (and URLs) are hard :)

When I'm in South Africa, I'll get a URL like this: https://www.google.co.za/maps/@-34.0861882,18.3838688,14z?hl=en

When I'm in the UK, I'll get a URL like this - and what's more, a lot of map links now appear under `/maps/place/` path:
https://www.google.co.uk/maps/place/14+Dufferin+St,+London+EC1Y+8PD/@51.5163255,-0.0872001,15z/data=!4m2!3m1!1s0x48761ca854662807:0xf59e8fc1e225056b?hl=en

**Comment by iparamonau** [comment]
Those two work fine at the moment:

* http://iframely.com/debug?uri=https%3A%2F%2Fwww.google.co.za%2Fmaps%2F%40-34.0861882%2C18.3838688%2C14z%3Fhl%3Den
* http://iframely.com/debug?uri=https%3A%2F%2Fwww.google.co.uk%2Fmaps%2Fplace%2F14%2BDufferin%2BSt%2C%2BLondon%2BEC1Y%2B8PD%2F%4051.5163255%2C-0.0872001%2C15z%2Fdata%3D!4m2!3m1!1s0x48761ca854662807%3A0xf59e8fc1e225056b%3Fhl%3Den

It's because we get re-routed to old URL and it's covered:


   -- plugin redirect (by "htmlparser") https://maps.google.co.za/maps?ll=-34.0861882,18.3838688&z=14&output=classic&dg=ntvb

The only thing that isn't covered is the Street View. We are monitoring it, and as soon as Google stops re-directing us we'll have to do a new plugin.

**Comment by suprememoocow** [comment]
Cool, thanks for checking. No idea why it wasn't working for me. I'll double-check when I make those changes..

**Comment by iparamonau** [comment]
Yes, thanks. If it still doesn't work let me know what user-agent you have in your local config. Perhaps, Google give you a special treatment :)

**Comment by iparamonau** [comment]
So Google finally stopped re-directing our user-agent to the old URL patterns. 

There's now new maps plugin in `develop` branch. It give 400x400 thumbnails by default. Requires Google Maps API key though.

Since you were doing changes in the old plugin, I will have to ask you to repeat those for the new plugin, if you still need it. Closing this PR for now.

Cheers,
Ivan.

**Pull request closed without merging**
