### PR TITLE
Add strawpoll.me iframe embed support

### PR DESCRIPTION
**Pull request by BenLubar**

### CODE REVIEW

**Comment by BenLubar** [comment]
The embed is really short even though I have height set to 750 on the iframe. Example: https://what.thedailywtf.com/post/1136686

**Comment by iparamonau** [comment]
That's because you return embed code as HTML, but don't have the flag "inline" in the rels. In that case, Iframely assumes that the embed code needs to be wrapped up into /render iFrame. But since you don't have the width and height - iFrames falls back to a responsive sizing with default aspect-ratio.

The correct way would be to give embed's iFrame src as `href` attribute, plus add `width` and `height`. Or even better - just the `height` alone (it will become a horizontal responsive iFrame). 
----

We saw strawpoll before, for sure. Unfortunately, we could not find a way to accurately detect the height of the embed and so we could not reliably support this publisher at the moment. I see you hardcode the sizes too, and this isn't right either. The smaller ones will look terrible, the longer ones will not fit. Here's an example of the longer one: http://www.strawpoll.me/12647245
 
So for now we will keep strawpoll excluded from package. If you do need a hardcoded solution, you could keep that domain plugin in local folder for custom plugins. See `CUSTOM_PLUGINS_PATH` in config example.

**Comment by iparamonau** [comment]
Now that closed the PR, I actually see a hacky way to detect the height. Let me put the proper plugin together.

**Comment by iparamonau** [comment]
I see you have started to change it yourself. Please re-open the PR once ready. The dependency to $selector should be renamed to `cheerio` - that way Iframely's core will take of it.

**Pull request closed without merging**
