### PR TITLE
Add buzzlike domain to the list of available domain plugins

### PR DESCRIPTION
**Pull request by JnKollo**
Hi iframely team !

I wrote this plugin for professional use but I think it could be included by default in iframely.

Let me know if there are something missing or to add.

Have a nice day.

### CODE REVIEW

**Comment by nihaux** [comment]
Hello @nleush @iparamonau anything blocking this ? My team and I would need this :)
Thx!

**Comment by iparamonau** [comment]
@nihaux the plugin needs a bit of love. We'll merge soon, just in time for the new version.

**Comment by nleush** [comment]
Thanks, merged and will update in npm today.

**Comment by nihaux** [comment]
thx ! @nleush

**Pull request closed without merging**
